site_name: editions/2023
docs_dir: .

extra:
  alternate:
    - name: Bahasa (Indonesian)
      lang: id
    - name: English
      lang: en
    - name: Français
      lang: fr
    - name: Persian
      lang: fa
    - name: Português (Portugal)
      lang: pt-pt
